### ISSUE TITLE
Do not use `Station.min_obs_time` and `Station.max_obs_time`

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/station-data-portal-backend#6]
See https://github.com/pacificclimate/pycds/issues/19 for why.

PDP currently uses (only) `CrmpNetworkGeoserver.min_obs_time` and `CrmpNetworkGeoserver.max_obs_time` instead. These are derived from the table `station_obs_stats_mv` (~~which incidentally is *not* mapped by PyCDS~~), which in turn computes these directly from `obs_raw.obs_time`. We should be using `CrmpNetworkGeoserver` likewise in here.

Although it may be slightly confusing for those with memories of the prior situation, it does make sense to continue serving these data values as the attributes `min_obs_time` and `max_obs_time` in `/stations` endpoints.

EDIT: `station_obs_stats_mv` is now mapped by pycds as `StationObservationStats`.

**Comment by faronium** [comment]
In an ideal world, the Station.min_obs_time (and max) would be populated by meta-data and would reflect the known period of record for the stations while the derived min_obs_time (and max) would reflect what we have in the database. The difference may be useful to a user who wants to hunt down the balance of the data. The latest ECCC station inventories have the min and max years for each station, so this could be used to populate the Station.min_obs_time (and max) so that's a route for one of the major networks. I can check the CRMP station inventories for more information for BC stations. Anyhow, I agree that the values in the station table shouldn't be used until more work is done on the station meta data some time down the road. I hope this comment is useful.

**Comment by rod-glover** [comment]
The comment is very useful, and raises some questions about which times to use for selecting stations in the frontend. Any advice on this would be very welcome.

**Comment by rod-glover** [comment]
There is now a good solution for this continuing problem. First, to explain the problem:
- `Station.min_obs_time` and `Station.max_obs_time` are dynamic values except for active stations.
- They are derived from other data in the database, so they are denormalized values, which is something to be avoided.
- Such derived values should be presented in views or matviews, which are explicitly derived and not primary.
- Even if we were happy with denormalized columns in the database, they are not being kept up to date. No entity or task has been established that is responsible for this.

Solution: 
- A recent update to PyCDS added columns `start_time` and `end_time` to the matview `VarsPerHistory` / `vars_per_history_mv`. These columns give the min and max times of observations by variable and history. 
- A simple query against `VarsPerHistory` will extract the values that `Station.min_obs_time` and `Station.max_obs_time` should have but frequently do not. This query is cheap enough, given `VarsPerHistory`, that there is no need for any additional matview to maintain these values.
- `VarsPerHistory` is already regularly maintained, so there is no need to establish any additional task.

**Comment by rod-glover** [comment]
This description was slightly hasty, and neglected the existence of the matview `StationObsStats`, which contains columns `min_obs_time` and `max_obs_time`. These columns are intended to replace usage of the problematic `Station` columns.

At present, the query for `StationObsStats` scans the entire `Obs` table, replicating work that `VarsPerHistory` now does. It may be a good idea to update that query accordingly. This procedure does have the disadvantage of introducing a sequence dependency between these two matviews.

**Comment by rod-glover** [comment]
The frontend uses only the obs times that are part of the history associated with the station. The history responses are obtained in the backend from `StationObservationStats`, whose values are computed only from the observations actually in the database.

Therefore, at present, this issue is a non-issue and can be closed.
